// Database types for Supabase
// This file will be auto-generated by Supabase CLI in production
// For now, we define the types manually based on our schema

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string | null;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          timezone: string;
          is_anonymous: boolean;
          community_visible: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          timezone?: string;
          is_anonymous?: boolean;
          community_visible?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          timezone?: string;
          is_anonymous?: boolean;
          community_visible?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      sobriety_records: {
        Row: {
          id: string;
          user_id: string;
          substance_type: 'alcohol' | 'drugs' | 'gambling' | 'custom';
          custom_label: string | null;
          start_date: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          substance_type: 'alcohol' | 'drugs' | 'gambling' | 'custom';
          custom_label?: string | null;
          start_date: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          substance_type?: 'alcohol' | 'drugs' | 'gambling' | 'custom';
          custom_label?: string | null;
          start_date?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      check_ins: {
        Row: {
          id: string;
          user_id: string;
          check_in_date: string;
          check_in_time: string;
          mood_rating: number | null;
          energy_level: number | null;
          craving_level: number | null;
          notes: string | null;
          is_sober: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          check_in_date: string;
          check_in_time: string;
          mood_rating?: number | null;
          energy_level?: number | null;
          craving_level?: number | null;
          notes?: string | null;
          is_sober?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          check_in_date?: string;
          check_in_time?: string;
          mood_rating?: number | null;
          energy_level?: number | null;
          craving_level?: number | null;
          notes?: string | null;
          is_sober?: boolean;
          created_at?: string;
        };
      };
      milestones: {
        Row: {
          id: string;
          user_id: string;
          sobriety_record_id: string;
          milestone_type: string;
          achieved_at: string;
          celebrated: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          sobriety_record_id: string;
          milestone_type: string;
          achieved_at: string;
          celebrated?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          sobriety_record_id?: string;
          milestone_type?: string;
          achieved_at?: string;
          celebrated?: boolean;
          created_at?: string;
        };
      };
      emergency_resources: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          phone_number: string | null;
          website_url: string | null;
          resource_type: 'hotline' | 'treatment_center' | 'support_group' | 'crisis_line';
          coverage_level: 'national' | 'regional' | 'local';
          country_code: string;
          region: string | null;
          city: string | null;
          is_24_hours: boolean;
          languages: string[];
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          phone_number?: string | null;
          website_url?: string | null;
          resource_type: 'hotline' | 'treatment_center' | 'support_group' | 'crisis_line';
          coverage_level: 'national' | 'regional' | 'local';
          country_code?: string;
          region?: string | null;
          city?: string | null;
          is_24_hours?: boolean;
          languages?: string[];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          phone_number?: string | null;
          website_url?: string | null;
          resource_type?: 'hotline' | 'treatment_center' | 'support_group' | 'crisis_line';
          coverage_level?: 'national' | 'regional' | 'local';
          country_code?: string;
          region?: string | null;
          city?: string | null;
          is_24_hours?: boolean;
          languages?: string[];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      branding_config: {
        Row: {
          id: string;
          primary_color: string;
          secondary_color: string;
          accent_color: string;
          logo_url: string | null;
          app_name: string;
          tagline: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          primary_color?: string;
          secondary_color?: string;
          accent_color?: string;
          logo_url?: string | null;
          app_name?: string;
          tagline?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          primary_color?: string;
          secondary_color?: string;
          accent_color?: string;
          logo_url?: string | null;
          app_name?: string;
          tagline?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

// Helper types for easier use
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type SobrietyRecord = Database['public']['Tables']['sobriety_records']['Row'];
export type CheckIn = Database['public']['Tables']['check_ins']['Row'];
export type Milestone = Database['public']['Tables']['milestones']['Row'];
export type EmergencyResource = Database['public']['Tables']['emergency_resources']['Row'];
export type BrandingConfig = Database['public']['Tables']['branding_config']['Row'];
